#!/bin/bash
# Auto-generate README.md for each agent directory
# Usage: ./generate-readmes.sh

AGENTS_DIR="/mnt/bounty/Claude/pi-agents"
BLUEPRINT_DIR="/mnt/bounty/Claude/pi-agents/swarm-blueprint"

echo "[*] Generating README files for all agents..."

# Iterate through all agent directories
for AGENT_DIR in "$AGENTS_DIR"/*/; do
  # Skip the blueprint directory
  if [[ "$AGENT_DIR" == *"swarm-blueprint"* ]]; then
    continue
  fi

  AGENT_NAME=$(basename "$AGENT_DIR")
  EXTENSION_FILE="$AGENT_DIR/extension.ts"
  RUN_FILE="$AGENT_DIR/run.sh"
  README_FILE="$AGENT_DIR/README.md"

  # Skip if no extension.ts or run.sh exists
  if [ ! -f "$EXTENSION_FILE" ] && [ ! -f "$RUN_FILE" ]; then
    echo "[-] Skipping $AGENT_NAME (no extension.ts or run.sh found)"
    continue
  fi

  echo "[+] Generating README for $AGENT_NAME..."

  # Extract data from extension.ts
  DESCRIPTION="(No description)"
  TIER="Unknown"
  MODEL="Unknown"
  TOOLS=""
  CHANNELS=""

  if [ -f "$EXTENSION_FILE" ]; then
    # Extract description from first JSDoc comment
    DESC_RAW=$(sed -n '/\/\*\*/,/\*\//p' "$EXTENSION_FILE" | grep -v '^\s*\*\s*$' | head -20)
    if [ -n "$DESC_RAW" ]; then
      DESCRIPTION=$(echo "$DESC_RAW" | sed 's/\/\*\*//g; s/\*\///g; s/^\s*\*\s*//g' | grep -E "JOB:|Tier:" | head -5)
    fi

    # Extract tier from system prompt
    TIER=$(grep -oP "Tier:\s+\K[A-Z]+" "$EXTENSION_FILE" | head -1)
    [ -z "$TIER" ] && TIER="OBSERVE"

    # Extract tools from registerTool calls
    TOOLS=$(grep -oP 'name:\s*"\K[^"]+' "$EXTENSION_FILE" | tr '\n' ', ' | sed 's/,$//')

    # Extract Discord channels from post_discord calls or webhook lookups
    CHANNELS=$(grep -oP 'webhooks\["\K[^"]+' "$EXTENSION_FILE" | sort -u | tr '\n' ', ' | sed 's/,$//')
  fi

  # Extract model and schedule from run.sh
  SCHEDULE="On-demand"
  if [ -f "$RUN_FILE" ]; then
    MODEL=$(grep -oP -- '--model\s+\K[^\s\\]+' "$RUN_FILE" | head -1)
    [ -z "$MODEL" ] && MODEL="NONE (bash)"

    # Check if there's a cron comment
    CRON_INFO=$(grep -E "^#.*Cron:" "$RUN_FILE" | head -1)
    if [ -n "$CRON_INFO" ]; then
      SCHEDULE=$(echo "$CRON_INFO" | sed 's/^#.*Cron:\s*//')
    fi
  fi

  # Generate README.md
  cat > "$README_FILE" << EOF
# $AGENT_NAME

> Auto-generated agent documentation

## Overview

**Tier:** $TIER
**Model:** $MODEL
**Schedule:** $SCHEDULE

## Description

$DESCRIPTION

## Tools

Available tools registered by this agent:

\`\`\`
$TOOLS
\`\`\`

## Discord Channels

Posts to the following channels:

\`\`\`
$CHANNELS
\`\`\`

## State Files

- \`state/last-run.log\` — Latest execution log
- \`state/last-run.json\` — Structured run summary
- \`state/audit.log\` — Governance audit trail

## Files

- \`extension.ts\` — Pi agent extension (tools, system prompt)
- \`run.sh\` — Launcher script with governance pre-flight
- \`preflight.sh\` — Data gathering script (if applicable)

## Running Manually

\`\`\`bash
cd $AGENT_DIR
./run.sh
\`\`\`

## Architecture

This agent follows the Pi Agent Swarm architecture:

1. **Pre-flight governance check** — Validates OPSEC, scope, kill switches
2. **Agent execution** — Pi runs with extension.ts loaded
3. **Tool execution** — Agent calls registered tools to complete workflow
4. **Discord posting** — Results posted to assigned channels
5. **State saving** — Run state persisted to disk

## Governance

- **Kill switch:** \`/tmp/agent-kill-$AGENT_NAME\`
- **Global halt:** \`/tmp/swarm-halt\`
- **OPSEC check:** \`/tmp/opsec-red\` (blocks Tier 2+ agents)
- **Audit log:** \`state/audit.log\`

See [\`GOVERNANCE-GUIDE.md\`](../swarm-blueprint/GOVERNANCE-GUIDE.md) for full governance rules.

---

*Generated by \`generate-readmes.sh\` — $(date -u +%Y-%m-%dT%H:%M:%SZ)*
EOF

  echo "    → $README_FILE"
done

echo ""
echo "[+] All READMEs generated!"
echo "[i] To regenerate, run: $BLUEPRINT_DIR/generate-readmes.sh"
