#!/bin/bash
# === GOVERNANCE PRE-FLIGHT ===
# Source this at the top of every agent's run.sh:
#   source /app/pi-agents/swarm-blueprint/preflight-governance.sh
#
# Required vars before sourcing:
#   AGENT_HOME — agent's home directory
#   AGENT_TIER — 0=OBSERVE, 1=MONITOR, 2=RECON, 3=SCAN, 4=EXPLOIT
#   TARGET     — (optional) target domain if applicable

# Don't use 'set -euo pipefail' here since this file is sourced
# and would affect the parent script's error handling

# Validate required variables
if [ -z "${AGENT_HOME:-}" ]; then
  echo "[ERROR] AGENT_HOME not set — cannot proceed with governance checks" >&2
  exit 1
fi

if [ -z "${AGENT_TIER:-}" ]; then
  echo "[ERROR] AGENT_TIER not set — cannot proceed with governance checks" >&2
  exit 1
fi

AGENT_NAME=$(basename "$AGENT_HOME")
GOV_DIR="/app/pi-agents/swarm-blueprint"
AUDIT_LOG="$AGENT_HOME/state/audit.log"

# Normalize AGENT_TIER: accept names or numbers
case "${AGENT_TIER}" in
  OBSERVE|observe) AGENT_TIER=0 ;;
  MONITOR|monitor) AGENT_TIER=1 ;;
  RECON|recon)     AGENT_TIER=2 ;;
  SCAN|scan)       AGENT_TIER=3 ;;
  EXPLOIT|exploit) AGENT_TIER=4 ;;
  [0-4])           ;; # already a number
  *)               echo "[WARNING] Unknown AGENT_TIER '$AGENT_TIER' — defaulting to 0" >&2; AGENT_TIER=0 ;;
esac

# Ensure state directory exists
mkdir -p "$AGENT_HOME/state" 2>/dev/null || {
  echo "[ERROR] Cannot create state directory at $AGENT_HOME/state" >&2
  exit 1
}

governance_log() {
  local msg="$1"
  local timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u)
  echo "[$timestamp] [TIER-$AGENT_TIER] [$AGENT_NAME] $msg" >> "$AUDIT_LOG" 2>/dev/null || {
    echo "[WARNING] Failed to write to audit log: $AUDIT_LOG" >&2
  }
}

# Log preflight start
governance_log "PREFLIGHT: Starting governance checks"

# ── CHECK 0: ORGANIZATIONAL AWARENESS ──
# Read swarm-state.json (generated by manager heartbeat every 120s)
# Exports SWARM_* env vars so agents understand the org at runtime
SWARM_STATE_JSON="$GOV_DIR/swarm-state.json"
if [ -f "$SWARM_STATE_JSON" ]; then
  # Check freshness (stale if >600s old)
  _swarm_mtime=$(stat -c %Y "$SWARM_STATE_JSON" 2>/dev/null || echo 0)
  _swarm_now=$(date +%s)
  SWARM_STATE_AGE=$(( _swarm_now - _swarm_mtime ))
  export SWARM_STATE_AGE

  if [ "$SWARM_STATE_AGE" -gt 600 ]; then
    export SWARM_STATE="stale"
    governance_log "WARNING: swarm-state.json is ${SWARM_STATE_AGE}s old (stale)"
  else
    export SWARM_STATE="fresh"
  fi

  # Parse key fields with jq (lightweight — only extract what agents need)
  if command -v jq >/dev/null 2>&1; then
    # Org mode (operational/degraded/maintenance/emergency)
    SWARM_MODE=$(jq -r '.org.mode // "operational"' "$SWARM_STATE_JSON" 2>/dev/null)
    export SWARM_MODE

    # Total agent count
    SWARM_AGENT_COUNT=$(jq -r '.agents.total // 0' "$SWARM_STATE_JSON" 2>/dev/null)
    export SWARM_AGENT_COUNT

    # This agent's status from the roster
    SWARM_MY_STATUS=$(jq -r --arg name "$AGENT_NAME" '.agents.roster[$name].status // "unknown"' "$SWARM_STATE_JSON" 2>/dev/null)
    export SWARM_MY_STATUS

    # This agent's division
    SWARM_MY_DIVISION=$(jq -r --arg name "$AGENT_NAME" '.agents.roster[$name].division // "unknown"' "$SWARM_STATE_JSON" 2>/dev/null)
    export SWARM_MY_DIVISION

    # Down services (comma-separated)
    SWARM_SERVICES_DOWN=$(jq -r '[.services | to_entries[] | select(.value.status == "down" or .value.status == "disconnected") | .key] | join(",")' "$SWARM_STATE_JSON" 2>/dev/null)
    export SWARM_SERVICES_DOWN

    # Paused agents (comma-separated)
    SWARM_PAUSED_AGENTS=$(jq -r '[.agents.roster | to_entries[] | select(.value.status == "paused") | .key] | join(",")' "$SWARM_STATE_JSON" 2>/dev/null)
    export SWARM_PAUSED_AGENTS

    # Maintenance mode — non-essential agents skip
    if [ "$SWARM_MODE" = "maintenance" ] && [ "${AGENT_TIER:-0}" -lt 1 ]; then
      governance_log "BLOCKED: Org in maintenance mode — Tier 0 agents skipped"
      echo "[HALT] Maintenance mode — non-essential agent skipping" >&2
      exit 0
    fi

    # If this agent is marked as paused in swarm-state, exit
    if [ "$SWARM_MY_STATUS" = "paused" ]; then
      governance_log "BLOCKED: Agent marked as PAUSED in swarm-state.json"
      echo "[HALT] Agent $AGENT_NAME is PAUSED — skipping" >&2
      exit 0
    fi

    governance_log "ORG AWARE: mode=$SWARM_MODE agents=$SWARM_AGENT_COUNT division=$SWARM_MY_DIVISION status=$SWARM_MY_STATUS"
  else
    governance_log "WARNING: jq not installed — swarm-state.json cannot be parsed"
    export SWARM_STATE="unparsed"
    export SWARM_MODE="operational"
  fi
else
  # No swarm-state.json yet — manager hasn't run or file was deleted
  export SWARM_STATE="missing"
  export SWARM_MODE="operational"
  export SWARM_STATE_AGE=999999
  governance_log "INFO: No swarm-state.json found — running without org awareness"
fi

# 1. Global kill switch
if [ -f /tmp/swarm-halt ]; then
  governance_log "BLOCKED: Global swarm halt active"
  echo "[HALT] Global kill switch active — exiting" >&2
  exit 0
fi

# 2. Agent-specific kill switch
if [ -f "/tmp/agent-kill-$AGENT_NAME" ]; then
  governance_log "BLOCKED: Agent killed by supervisor"
  echo "[HALT] Agent $AGENT_NAME killed — exiting" >&2
  exit 0
fi

# 3. OPSEC check (Tier 2+ only)
if [ "${AGENT_TIER:-0}" -ge 2 ] && [ -f /tmp/opsec-red ]; then
  governance_log "BLOCKED: OPSEC RED — Tier $AGENT_TIER requires VPN"
  echo "[HALT] OPSEC RED — Tier $AGENT_TIER agent cannot run without VPN" >&2
  exit 0
fi

# 4. Scope check (Tier 2+ with target)
if [ -n "${TARGET:-}" ] && [ "${AGENT_TIER:-0}" -ge 2 ]; then
  SCOPE_FILE="$GOV_DIR/approved-scope.json"
  if [ -f "$SCOPE_FILE" ]; then
    IN_SCOPE=$(python3 -c "
import json, sys
try:
    scope = json.load(open('$SCOPE_FILE'))
    target = '$TARGET'
    domains = scope.get('domains', [])
    wildcards = scope.get('wildcards', [])
    excluded = scope.get('excluded', [])
    # Check exact match
    if target in domains:
        print('YES')
        sys.exit(0)
    # Check wildcard match
    for w in wildcards:
        if w.startswith('*.') and target.endswith(w[1:]):
            print('YES')
            sys.exit(0)
    # Check excluded
    if target in excluded:
        print('EXCLUDED')
        sys.exit(0)
    print('NO')
except Exception as e:
    print(f'ERROR: {e}', file=sys.stderr)
    print('ERROR')
" 2>/dev/null)

    if [ "$IN_SCOPE" = "ERROR" ]; then
      governance_log "ERROR: Failed to parse scope file"
      echo "[ERROR] Scope check failed — cannot verify target authorization" >&2
      exit 1
    fi

    if [ "$IN_SCOPE" = "EXCLUDED" ]; then
      governance_log "BLOCKED: Target $TARGET is explicitly excluded from scope"
      echo "[HALT] Target $TARGET is EXCLUDED from scope" >&2
      exit 0
    fi

    if [ "$IN_SCOPE" != "YES" ]; then
      governance_log "BLOCKED: Target $TARGET not in approved scope"
      echo "[HALT] Target $TARGET not in approved scope — ask Commander to add it" >&2
      exit 0
    fi
  else
    governance_log "WARNING: Scope file not found at $SCOPE_FILE — proceeding without scope check"
    echo "[WARNING] Scope file missing — cannot verify target authorization" >&2
  fi
fi

# 5. Rate limit check (Tier 3+ with target)
if [ -n "${TARGET:-}" ] && [ "${AGENT_TIER:-0}" -ge 3 ]; then
  RATE_DIR="/tmp/rate-counters"
  mkdir -p "$RATE_DIR" 2>/dev/null
  RATE_FILE="$RATE_DIR/$(echo $TARGET | tr '.' '_').count"
  if [ -f "$RATE_FILE" ]; then
    CURRENT_RATE=$(cat "$RATE_FILE" 2>/dev/null || echo "0")
    HARD_LIMIT=500  # requests per hour
    if [ "${CURRENT_RATE:-0}" -ge "$HARD_LIMIT" ]; then
      governance_log "BLOCKED: Rate limit reached for $TARGET ($CURRENT_RATE/$HARD_LIMIT)"
      echo "[HALT] Rate limit reached for $TARGET — try again next hour" >&2
      exit 0
    fi
  fi
fi

# ═══════════════════════════════════════
# INCIDENT REPORTING — Shared by ALL agents
# ═══════════════════════════════════════
# Usage: report_incident "agent-failures" "Agent crashed with exit code 1"
# Types: agent-failures, opsec-violations, resource-alerts, remediation-log, service-outages
# Reads webhook URLs from centralized incident-webhooks.json

INCIDENT_CONFIG="$GOV_DIR/incident-webhooks.json"

report_incident() {
  local incident_type="${1:-agent-failures}"
  local message="${2:-No details provided}"
  local reporter="${AGENT_NAME:-unknown}"
  local timestamp
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -u)

  # Maintenance suppression: if a maintenance window is active and covers this service, log locally only
  if [ -f /tmp/swarm-maintenance ] && command -v python3 &>/dev/null; then
    local _suppress
    _suppress=$(python3 -c "
import json, sys
try:
    mw = json.load(open('/tmp/swarm-maintenance'))
    if mw.get('suppress_alerts'):
        for svc in mw.get('affected_services', []):
            if svc.lower() in '''$message'''.lower():
                print('yes'); sys.exit(0)
except: pass
print('no')
" 2>/dev/null)
    if [ "$_suppress" = "yes" ]; then
      governance_log "SUPPRESSED: Incident during maintenance window: [$incident_type] $message"
      echo "[$timestamp] [SUPPRESSED] [$incident_type] [$reporter] $message" >> "$AGENT_HOME/state/incidents.log" 2>/dev/null || true
      return 0
    fi
  fi

  # Get webhook URL from centralized config
  local webhook_url=""
  if [ -f "$INCIDENT_CONFIG" ] && command -v python3 &>/dev/null; then
    webhook_url=$(python3 -c "
import json, sys
try:
    cfg = json.load(open('$INCIDENT_CONFIG'))
    entry = cfg.get('$incident_type', {})
    print(entry.get('webhook_url', ''))
except:
    pass
" 2>/dev/null)
  fi

  if [ -z "$webhook_url" ]; then
    governance_log "WARNING: No webhook for incident type '$incident_type' — logging locally only"
    echo "[$timestamp] [$incident_type] [$reporter] $message" >> "$AGENT_HOME/state/incidents.log" 2>/dev/null || true
    return 1
  fi

  # Post to Discord incident channel
  local formatted_msg
  formatted_msg="🚨 **INCIDENT** | \`$incident_type\`
**Reporter:** \`$reporter\`
**Time:** \`$timestamp\`
**Details:** $message"

  # Truncate to Discord limit
  if [ ${#formatted_msg} -gt 1950 ]; then
    formatted_msg="${formatted_msg:0:1947}..."
  fi

  curl -s -X POST "$webhook_url" \
    -H "Content-Type: application/json" \
    -d "$(python3 -c "
import json, sys
msg = '''$formatted_msg'''
print(json.dumps({'content': msg, 'username': '🚨 $reporter'}))
" 2>/dev/null || echo '{"content":"incident report failed","username":"error"}')" \
    > /dev/null 2>&1 || true

  # Also post to inc-new (lifecycle: all new incidents start here)
  local new_webhook=""
  if [ -f "$INCIDENT_CONFIG" ]; then
    new_webhook=$(python3 -c "
import json
try:
    cfg = json.load(open('$INCIDENT_CONFIG'))
    print(cfg.get('new', {}).get('webhook_url', ''))
except:
    pass
" 2>/dev/null)
  fi

  if [ -n "$new_webhook" ]; then
    curl -s -X POST "$new_webhook" \
      -H "Content-Type: application/json" \
      -d "$(python3 -c "
import json
msg = '🆕 **NEW INCIDENT** | \`$incident_type\` | from \`$reporter\`\n$message'
print(json.dumps({'content': msg[:1950], 'username': '🆕 Triage Queue'}))" 2>/dev/null)" \
      > /dev/null 2>&1 || true
  fi

  # Log locally
  governance_log "INCIDENT: [$incident_type] $message"
  echo "[$timestamp] [$incident_type] [$reporter] $message" >> "$AGENT_HOME/state/incidents.log" 2>/dev/null || true

  return 0
}

# All checks passed
governance_log "APPROVED: Agent starting (Tier $AGENT_TIER, Target: ${TARGET:-none})"
echo "[+] Governance pre-flight passed — Tier $AGENT_TIER authorized"
